- project:
    templates:
      - openstack-python3-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-functional-py39:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py310:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py311:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py312:
            required-projects:
              - openstack/placement
    gate:
      jobs:
        - openstack-tox-functional-py39:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py310:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py311:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py312:
            required-projects:
              - openstack/placement
