- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-functional:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py36:
            required-projects:
              - openstack/placement
    gate:
      jobs:
        - openstack-tox-functional:
            required-projects:
              - openstack/placement
        - openstack-tox-functional-py36:
            required-projects:
              - openstack/placement
